### ISSUE TITLE
author part of draft filename

### ISSUE THREAD

**Issue by dret** [sdatspun2/deprecation-header#1]
i may be wrong, but i am pretty sure that the convention is to name individual drafts with one author name, following the `draft-...` pattern.
brief check at https://www.ietf.org/standards/ids/guidelines/ and indeed: "A string related to the name of one of the authors in some way. There are no mechanical rules for this string but objectionable or misleading strings are subject to change or removal at the discretion of the Secretariat."

**Comment by sdatspun2** [comment]
this was changed.
