### ISSUE TITLE
Use IMF-fixdate instead of HTTP-date

### ISSUE THREAD

**Issue by ioggstream** [sdatspun2/deprecation-header#18]
## I expect

The date format MUST be the `IMF-fixdate syntax for the HTTP-date`

see  https://tools.ietf.org/html/rfc7231#section-7.1.1.1

## Instead

It uses HTTP-date, which includes support for `obs-date`

```
HTTP-date = IMF-fixdate / obs-date
```

iiuc  rfc7231 § 7.1.1.1 contains a  discussion on the subject which should be repeated here if we don't forbid obs-date

**Comment by dret** [comment]
On 2019-08-28 11:35, Roberto Polli wrote:
> The date format MUST be the |IMF-fixdate syntax for the HTTP-date|
> see https://tools.ietf.org/html/rfc7231#section-7.1.1.1

thanks for noticing. i guess that would have been a better choice for 
the sunset header field as well, but it's too late for that one now:

https://tools.ietf.org/html/rfc8594#section-3

**Comment by ioggstream** [comment]
My bad I didn't notice your work :( 

I think everybody will use the IMF-fixdate format though. I just discovered that `obs-date` stuff when reading RFC7231 and wanted to simplify the life of implementors avoiding old stuff to linger around.

**Comment by dret** [comment]
On 2019-08-28 12:49, Roberto Polli wrote:
> I think everybody will use the IMF-fixdate format though. I just 
> discovered that |obs-date| stuff when reading RFC7231 and wanted to 
> simplify the life of implementors avoiding old stuff to linger around.

absolutely agreed. i just didn't read all/enough of RFC 7231 when i went 
hunting for a timestamp definition to reuse...
