### ISSUE TITLE
Add example response for deprecating query parameters / methods

### ISSUE THREAD

**Issue by ioggstream** [sdatspun2/deprecation-header#19]
## I wish

an example response for deprecating query parameters or method

## Note

iiuc as of now, only a resource-target deprecation is shown.

**Comment by dret** [comment]
On 2019-08-28 11:50, Roberto Polli wrote:
>     I wish
> an example response for deprecating query parameters or method

please see #8 which explains that this is only about resource deprecation.

>     Note
> iiuc as of now, only a resource-target deprecation is shown.

true, but that's a design choice (note that #16 has essentially the same 
request).

**Comment by ioggstream** [comment]
moved under #8
