### ISSUE TITLE
scope in the deprecation header

### ISSUE THREAD

**Issue by sdatspun2** [sdatspun2/deprecation-header#4]
I was speaking to an API developer regarding the deprecation header. He suggested having scope would help. Scope could be request, response or endpoint. Documenting the ask in this issue.

**Comment by dret** [comment]
i am still concerned that it might get rather complex (missing the 80/20 rule by a lot) if we want to formally specify all the various bit and pieces of an API that can be affected by deprecation.

**Comment by sdatspun2** [comment]
i agree. this issue was created to record the ask. closing it.
