### ISSUE TITLE
Is there a need to provide limited amount of arbitrary text in Deprecation header?

### ISSUE THREAD

**Issue by sdatspun2** [sdatspun2/deprecation-header#6]
Is there a need to provide limited amount of arbitrary text in Deprecation header? As an example, take a look at the attached response for an Ajax call using sync property which is deprecated.

![xmlhttp_deprecation](https://user-images.githubusercontent.com/21368261/53121221-8cd09080-3508-11e9-878e-c5c8029b1c25.png)

**Comment by dret** [comment]
i'd be hesitant to allow UI-focused data. it would be rather unusual, probably would have to be very constrained, and might add internationalization headaches as well. with the link relation, we have a way to make documentation easily discoverable.

**Comment by sdatspun2** [comment]
agree. thanks. closing.
