### ISSUE TITLE
ABNF for version/date parameters

### ISSUE THREAD

**Issue by dret** [sdatspun2/deprecation-header#7]
given the current ABNF, it seems like a version parameter must occur before a date parameter, if both are used. that's probably not intentional, and should be changed to allow either sequence (and probably extensions should be allowed to be mixed in as well).

**Comment by dret** [comment]
possibly related to #9 (are multiple version identifiers possible), but even if only one is supported, the ABNF should be less constraining than it currently is.

**Comment by sdatspun2** [comment]
@dret Should we close this now?

**Comment by dret** [comment]
On 2019-06-11 16:02, Sanjay Dalal wrote:
> @dret <https://github.com/dret> Should we close this now?

we probably can, if the model remains as simple as it currently is.
