### ISSUE TITLE
how does the version identifier work?

### ISSUE THREAD

**Issue by dret** [sdatspun2/deprecation-header#9]
getting back to the draft i am still not quite sure about the way the version mechanism works. it seems to assume that there is a well-known (but opaque) version identifier that clients know and can use? how would they know it, and what would they use it for? would it be possible that various versions can show up as deprecated at the same URI?
if you could try to write a little more about how the version identifier is assigned, how clients learn about it, what kind of actions they are supposed to take when it shows up in a deprecation header field, that would be great. it might also help others to better understand the mechanism.

**Comment by sdatspun2** [comment]
>would it be possible that various versions can show up as deprecated at the same URI?
I haven't come across such a scenario.

>version identifier that clients know and can use? how would they know it, 
Often version identifiers are in path. Documentation also provides information about the versions. 

>and what would they use it for? 
To access the resource. I am not sure I understand this question.

>if you could try to write a little more about how the version identifier is assigned, how clients learn about it, what kind of actions they are supposed to take when it shows up in a deprecation header field, that would be great. it might also help others to better understand the mechanism.

Then it goes into versioning aspect and I am not sure we should go there since API developers might use different versioning strategy and naming.

**Comment by dret** [comment]
On 2019-04-21 08:01, Sanjay Dalal wrote:
> Then it goes into versioning aspect and I am not sure we should go there 
> since API developers might use different versioning strategy and naming.

my intention was not to try to tell people how to do their versioning.

but the current `version` model assumes that version identifiers are a 
meaningful thing to use (over just using timestamps as a self-describing 
data type). so the assumption must be that client developers somehow 
understand or at the very least know about these identifiers. how else 
would a message otherwise make sense to them?

so i think there has to be some text explaining how this works. how do 
they learn about version identifiers, so that when they see a 
deprecation header field referring to a version, it makes sense to them?

**Comment by sdatspun2** [comment]
>so the assumption must be that client developers somehow understand or at the very least know about these identifiers. how else would a message otherwise make sense to them?

Could we state that it is out of scope to explain how resource developer would or would not version the resource(s) and how resource versions are documented? However, provided that a resource has a version and assuming that the version could be identified by an identifier in the form of a string, the resource developer could notify the client developers about version of the deprecated resource using the `Deprecation` header if the deprecated resource is accessed. The resource developer could also use `Link` header and Link Relation Type named `deprecation` to inform the client developer about deprecation policy and resource documentation among other things.

**Comment by dret** [comment]
On 2019-05-02 16:45, Sanjay Dalal wrote:
>     so the assumption must be that client developers somehow understand
>     or at the very least know about these identifiers. how else would a
>     message otherwise make sense to them?
> 
> Could we state that it is out of scope to explain how resource developer 
> would or would not version the resource(s) and how resource versions are 
> documented? However, provided that a resource has a version and assuming 
> that the version could be identified by an identifier in the form of a 
> string, the resource developer could notify the client developers about 
> version of the deprecated resource using the |Deprecation| header if the 
> deprecated resource is accessed.

so again: what does it mean that a resource "has a version"? if by this 
you mean that there is a different resource with a different URI, all 
that matters is that the URI i am looking at declares itself deprecated 
at some time, and that i may be able to find an newer version via 
documentation or the versioning link relations.

i still don't understand how the "version" information enables the 
client to know or do anything specifically. maybe you could simply give 
an example of how this allows a client do anything that it couldn't just 
do when knowing the deprecation time?

**Comment by dret** [comment]
without a definition of what version identifiers identify, and what clients can do with them, my proposal is to stick with #8 and drop version identification. alternatively, if we want to keep it, we need an explanation how it is helping developers beyond simple timestamps.
if we drop them, #7 becomes easier as well, as we can reuse the syntax of `Sunset`.

**Comment by sdatspun2** [comment]
i am beginning to think your point :). version definition is definitely not in scope of this header, it is always in the scope where this header is applied (e.g. APIs). 

1. For API developers who use version in path (/v1) responding with this header and timestamp could sufficiently indicate that the version in context (v1) is deprecated on date given in the header. 
2. For API developers (like Stripe and Twilio), who use date-based versioning (see https://stripe.com/docs/api/versioning), their version format would be something like 2010-04-01 or 01-0402010, etc. How would timestamp format work for them?

```
 Deprecation: date="Fri, 11 Nov 2018 23:59:59 GMT"
```

To keep their versions in sync with value in Deprecation header and for ease of use, they might prefer

```
 Deprecation: version="2010-04-01"
```
or
```
 Deprecation: date="04 Apr 2010"
```

Let me know of your thoughts.

**Comment by dret** [comment]
On 2019-05-13 08:37, Sanjay Dalal wrote:
>  1. For API developers who use version in path (/v1) responding with
>     this header and timestamp could sufficiently indicate that the
>     version in context (v1) is deprecated on date given in the header.

good, i think we're in agreement.

>  2. For API developers (like Stripe and Twilio), who use date-based
>     versioning (see https://stripe.com/docs/api/versioning), their
>     version format would be something like 2010-04-01 or 01-0402010,
>     etc. How would timestamp format work for them?

as you said yourself, version identifiers are both opaque and not 
important at our level. twilio may use date strings, but they might as 
well use version numbers. in both cases, these identifiers are not 
relevant for us.

> |Deprecation: date="Fri, 11 Nov 2018 23:59:59 GMT" |
> 
> To keep their versions in sync with value in Deprecation header and for 
> ease of use, they might prefer
> 
> |Deprecation: version="2010-04-01" |
> 
> or
> 
> |Deprecation: date="04 Apr 2010" |

these are two very different things to say.

- the first one says "the version identified by the opaque string 
'2010-04-01'" is deprecated. and as i mentioned earlier, i still don't 
understand what this says about actual deprecation. when is it 
deprecated? and why would i need to give its version identifier, what 
would that be good for?

- the second one says "the context you are currently interacting with 
deprecates on '04 Apr 2010'". so that's actionable, and it doesn't need 
any version identifier.

> Let me know of your thoughts.

i know that i keep repeating myself and i am sorry, but i still do not 
see how the version identifier carries actionable information.

**Comment by sdatspun2** [comment]
Ok. ok. :) Have you come across instances where date is already used to convey deprecation? We have listed one instance in the draft, Zapier, who uses `X-API-Deprecation-Date`. Perhaps there are more and we should list those. 

I have always come across developers talking about deprecated versions. Rarely I have come across discussions where exact date of deprecation of a version is deemed important. It is easy to remember versions vs dates. Having said that, from scoping and actionable perspectives, I agree that only date would make sense.

**Comment by dret** [comment]
On 2019-05-14 12:39, Sanjay Dalal wrote:
> Ok. ok. :) Have you come across instances where date is already used to 
> convey deprecation? We have listed one instance in the draft, Zapier, 
> who uses |X-API-Deprecation-Date|. Perhaps there are more and we should 
> list those.

i have not looked for examples and cannot give additional ones. but 
you're right that deprecation probably is less in need of publishing a 
date in advance, even though that might be a useful thing to do.

> I have always come across developers talking about deprecated versions.

true, and in this case it's simply a flag, right? a resource either is 
deprecated or not.

> Rarely I have come across discussions where exact date of deprecation of 
> a version is deemed important. It is easy to remember versions vs dates. 
> Having said that, from scoping and actionable perspectives, I agree that 
> only date would make sense.

as mentioned above, i agree that dates are less important here than for 
sunsetting. when signaling a deprecated resource, any date in the past 
will do. i am not sure how often developers want to signal an upcoming 
deprecation.

would you suggest all we need is a boolean flag? maybe i am too much 
thinking about mirroring the "Sunset" design here.

**Comment by sdatspun2** [comment]
It is good to have date in case some API developers (like Zapier) want to use it, not mandatory though.

**Comment by dret** [comment]
On 2019-05-14 15:05, Sanjay Dalal wrote:
> It is good to have date in case some API developers (like Zapier) want 
> to use it, not mandatory though.

but then how does the header field look if there is no date?

* no value? (i am not sure this is even allowed)
* "true"
* something else?

i still think that you could always put a date in there, it simply could 
be the timestamp of when you start using the header, effectively 
(initially) saying "the resource is deprecated as of now".

**Comment by sdatspun2** [comment]
>* no value? (i am not sure this is even allowed)

This is a bummer. I think we could have a new key (no value) like: ? (meaning unknown). See https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Field_values esp

See: Pragma, Tk, Upgrade,

**Comment by dret** [comment]
On 2019-05-14 17:22, Sanjay Dalal wrote:
>       * no value? (i am not sure this is even allowed)
> 
> This is a bummer. I think we could have a new key (no value) like: ? 
> (meaning unknown). See 
> https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Field_values esp
> See: Pragma, Tk, Upgrade,

would you object to simply requiring a timestamp and get away with the 
same syntax as the Sunset header field? i am not sure it would be such a 
burden on developers to specify when deprecation was put into effect.

**Comment by sdatspun2** [comment]
The date field could be abused due to lack of knowledge of the exact date. Same argument: "Rarely I have come across discussions where exact date of deprecation of a version is deemed important. It is easy to remember versions vs dates." 

```
true; date=""
```
valid to have either or both

**Comment by dret** [comment]
On 2019-05-15 08:30, Sanjay Dalal wrote:
> The date field could be abused due to lack of knowledge of the exact 
> date. Same argument: "Rarely I have come across discussions where exact 
> date of deprecation of a version is deemed important. It is easy to 
> remember versions vs dates."
> 
> |true; date="" |
> 
> valid to have either or both

the thing is: we wouldn't have 'date=""' anymore if we switch to the 
sunset syntax (which has just the timestamp as the value of the header 
field). but we could choose to allow either timestamp or true. feels 
odd, though, and i am always a bit worried that having "union types" is 
something that many implementations fail to properly support.

**Comment by sdatspun2** [comment]
If you look at https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Field_values, you would find many response headers with name, value pairs including some not having value. So it is not going to be odd.

**Comment by dret** [comment]
On 2019-05-15 10:02, Sanjay Dalal wrote:
> If you look at 
> https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Field_values, 
> you would find many response headers with name, value pairs including 
> some not having value. So it is not going to be odd.

i don't see any. they all have values, but some have keywords as values 
(if that is what you mean). i don't think there is one without a value.

**Comment by sdatspun2** [comment]
attachment in Content-Disposition: attachment; filename="fname.ext"
mime type text/html in Content-Type: text/html; charset=utf-8

Retry-After is allows either types, non-negative integer (120) or date (HTTP-date)

    Example 1: Retry-After: 120
    Example 2: Retry-After: Fri, 07 Nov 2014 23:59:59 GMT

Similarly Vary allows wildcard and other values

    Example 1: Vary: *
    Example 2: Vary: Accept-Language

We could model like Retry-After. See https://tools.ietf.org/html/rfc7231#section-7.1.3

Deprecation: true
Deprecation: Fri, 07 Nov 2014 23:59:59 GMT

**Comment by sdatspun2** [comment]
Saw your changes. Closing.
